# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class CreateAssetReportRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateAssetReportRequest - a model defined in OpenAPI

        access_token: The access_token of this CreateAssetReportRequest.
        days_requested: The days_requested of this CreateAssetReportRequest.
        include_identity: The include_identity of this CreateAssetReportRequest [Optional].
    """

    access_token: str = Field(alias="access_token")
    days_requested: float = Field(alias="days_requested")
    include_identity: Optional[bool] = Field(alias="include_identity", default=None)

    @validator("days_requested")
    def days_requested_max(cls, value):
        assert value <= 365
        return value

    @validator("days_requested")
    def days_requested_min(cls, value):
        assert value >= 1
        return value

CreateAssetReportRequest.update_forward_refs()
