# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class FinancialConnectionsAccountCachedBalance(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    FinancialConnectionsAccountCachedBalance - a model defined in OpenAPI

        available: The available of this FinancialConnectionsAccountCachedBalance [Optional].
        current: The current of this FinancialConnectionsAccountCachedBalance [Optional].
        iso_currency_code: The iso_currency_code of this FinancialConnectionsAccountCachedBalance [Optional].
        last_updated_date: The last_updated_date of this FinancialConnectionsAccountCachedBalance [Optional].
    """

    available: Optional[float] = Field(alias="available", default=None)
    current: Optional[float] = Field(alias="current", default=None)
    iso_currency_code: Optional[str] = Field(alias="iso_currency_code", default=None)
    last_updated_date: Optional[str] = Field(alias="last_updated_date", default=None)

FinancialConnectionsAccountCachedBalance.update_forward_refs()
