# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SyncFinancialConnectionsDataResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SyncFinancialConnectionsDataResponse - a model defined in OpenAPI

        message: The message of this SyncFinancialConnectionsDataResponse [Optional].
        request_id: The request_id of this SyncFinancialConnectionsDataResponse [Optional].
    """

    message: Optional[str] = Field(alias="message", default=None)
    request_id: Optional[str] = Field(alias="request_id", default=None)

SyncFinancialConnectionsDataResponse.update_forward_refs()
