from looqbox.class_loader.lazy_load import LazyLoad
from looqbox.objects.component_utility.css_option import CssOption

@LazyLoad
def ObjMessage(*args, **kwargs): ...
@LazyLoad
def ObjImage(*args, **kwargs): ...
@LazyLoad
def ObjVideo(*args, **kwargs): ...
@LazyLoad
def ObjList(*args, **kwargs): ...
@LazyLoad
def ObjHTML(*args, **kwargs): ...
@LazyLoad
def ObjPDF(*args, **kwargs): ...
@LazyLoad
def ObjWebFrame(*args, **kwargs): ...
@LazyLoad
def ObjTable(*args, **kwargs): ...
@LazyLoad
def ObjPlotly(*args, **kwargs): ...
@LazyLoad
def ObjForm(*args, **kwargs): ...
@LazyLoad
def ObjImageCapture(*args, **kwargs): ...
@LazyLoad
def ObjEmbed(*args, **kwargs): ...
@LazyLoad
def ObjText(*args, **kwargs): ...
@LazyLoad
def ObjSimple(*args, **kwargs): ...
@LazyLoad
def ObjFormHTML(*args, **kwargs): ...
@LazyLoad
def ObjRow(*args, **kwargs): ...
@LazyLoad
def ObjColumn(*args, **kwargs): ...
@LazyLoad
def ObjSwitch(*args, **kwargs): ...
@LazyLoad
def ObjQuery(*args, **kwargs): ...
@LazyLoad
def ObjTooltip(*args, **kwargs): ...
@LazyLoad
def ObjLink(*args, **kwargs): ...
@LazyLoad
def ObjGauge(*args, **kwargs): ...
@LazyLoad
def ObjLine(*args, **kwargs): ...
@LazyLoad
def ObjFileUpload(*args, **kwargs): ...
@LazyLoad
def ObjAudio(*args, **kwargs): ...


__all__ = ["ObjTable", "ObjWebFrame", "ObjPlotly", "ObjPDF", "ObjList", "ObjHTML", "ObjImage",
           "ObjMessage", "ObjVideo", "ObjForm", "ObjFileUpload", "ObjImageCapture", "ObjEmbed",
           "ObjAudio", "ObjSimple", "ObjFormHTML", "ObjQuery", "ObjRow", "ObjColumn", "ObjSwitch",
           "ObjTooltip", "ObjLink", "ObjText", "ObjGauge", "ObjLine", "CssOption"]
