# Generated by Django 3.2 on 2021-06-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcd_geo_db', '0004_remove_division_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='path_temp',
            new_name='path',
        ),
    ]
