# Generated by Django 3.2 on 2022-02-16 11:49

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wcd_geo_db', '0015_auto_20220214_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='label',
            field=models.TextField(blank=True, db_index=True, verbose_name='Text label'),
        ),
    ]
