# Generated by Django 3.2 on 2022-02-17 07:31

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wcd_geo_db', '0016_auto_20220216_1149'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE wcd_geo_db_division ALTER COLUMN polygon type geography(MultiPolygon, 4326) using ST_Multi(polygon::geometry)::geography;",
            "ALTER TABLE wcd_geo_db_division ALTER COLUMN polygon type geography(Polygon, 4326) using ST_Polygon(polygon::geometry, 4326)::geography;",
            state_operations=[
                migrations.AlterField(
                    model_name='division',
                    name='polygon',
                    field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='Polygon'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='division',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='Polygon'),
        ),
        migrations.AlterField(
            model_name='division',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='wcd_geo_db.divisionprefix', verbose_name='Division name prefix'),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='Polygon'),
        ),
        migrations.AlterField(
            model_name='place',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='Polygon'),
        ),
        migrations.AlterField(
            model_name='route',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='Polygon'),
        ),
    ]
