# Generated by Django 3.2 on 2022-02-17 07:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcd_geo_db', '0017_auto_20220217_0731'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='division',
            name='wcd_geo_db_division_path_index',
        ),
        migrations.AddIndex(
            model_name='division',
            index=django.contrib.postgres.indexes.GistIndex(fields=['path'], name='wcd_geo_db_division_path_index', opclasses=('gist_ltree_ops(siglen=100)',)),
        ),
    ]
