cd ../;
cd ../;
cd Dockers_file;
echo "======================================= killing old docker processes =====================================";
docker stop __viper___app_container;
docker rm __viper___app_container;
echo "==================================== building kec_flask_app image =========================================";
docker build --progress=plain -f "./app/Dockerfile" -t __viper___app .;
echo "================================ building kec_flask_app_backup image ======================================";
docker image build -f "./app_backup/Dockerfile" -t __viper___app_backup .;
cd ../;
cd execute;
cd Linux;
echo "=============================================== Completed =================================================";