# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tarp.proto\x12\x03\x61rp\"+\n\x0bInfoRequest\x12\x12\n\x05\x66ield\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_field\"&\n\x07\x43ontact\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"$\n\x07License\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"y\n\x04Info\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x1d\n\x07\x63ontact\x18\x04 \x01(\x0b\x32\x0c.arp.Contact\x12\x1d\n\x07license\x18\x05 \x01(\x0b\x32\x0c.arp.License\"=\n\x12\x43omputationRequest\x12\x13\n\x0bworking_dir\x18\x01 \x01(\t\x12\x12\n\nfiles_name\x18\x02 \x01(\t\"5\n\x11\x43omputationResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2|\n\rAudioAnalyser\x12+\n\ngetAimInfo\x12\x10.arp.InfoRequest\x1a\t.arp.Info\"\x00\x12>\n\x07\x61nalyse\x12\x17.arp.ComputationRequest\x1a\x16.arp.ComputationResult\"\x00\x30\x01\x32|\n\rVideoAnalyser\x12+\n\ngetAimInfo\x12\x10.arp.InfoRequest\x1a\t.arp.Info\"\x00\x12>\n\x07\x61nalyse\x12\x17.arp.ComputationRequest\x1a\x16.arp.ComputationResult\"\x00\x30\x01\x32\x8a\x01\n\x1aTapeIrregularityClassifier\x12+\n\ngetAimInfo\x12\x10.arp.InfoRequest\x1a\t.arp.Info\"\x00\x12?\n\x08\x63lassify\x12\x17.arp.ComputationRequest\x1a\x16.arp.ComputationResult\"\x00\x30\x01\x32\x83\x01\n\x14TapeAudioRestoration\x12+\n\ngetAimInfo\x12\x10.arp.InfoRequest\x1a\t.arp.Info\"\x00\x12>\n\x07restore\x12\x17.arp.ComputationRequest\x1a\x16.arp.ComputationResult\"\x00\x30\x01\x32w\n\x08Packager\x12+\n\ngetAimInfo\x12\x10.arp.InfoRequest\x1a\t.arp.Info\"\x00\x12>\n\x07package\x12\x17.arp.ComputationRequest\x1a\x16.arp.ComputationResult\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFOREQUEST._serialized_start=18
  _INFOREQUEST._serialized_end=61
  _CONTACT._serialized_start=63
  _CONTACT._serialized_end=101
  _LICENSE._serialized_start=103
  _LICENSE._serialized_end=139
  _INFO._serialized_start=141
  _INFO._serialized_end=262
  _COMPUTATIONREQUEST._serialized_start=264
  _COMPUTATIONREQUEST._serialized_end=325
  _COMPUTATIONRESULT._serialized_start=327
  _COMPUTATIONRESULT._serialized_end=380
  _AUDIOANALYSER._serialized_start=382
  _AUDIOANALYSER._serialized_end=506
  _VIDEOANALYSER._serialized_start=508
  _VIDEOANALYSER._serialized_end=632
  _TAPEIRREGULARITYCLASSIFIER._serialized_start=635
  _TAPEIRREGULARITYCLASSIFIER._serialized_end=773
  _TAPEAUDIORESTORATION._serialized_start=776
  _TAPEAUDIORESTORATION._serialized_end=907
  _PACKAGER._serialized_start=909
  _PACKAGER._serialized_end=1028
# @@protoc_insertion_point(module_scope)
