# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from fuse_client.models.create_link_token_request_mx import CreateLinkTokenRequestMx
from fuse_client.models.create_link_token_request_plaid import CreateLinkTokenRequestPlaid
from fuse_client.models.entity import Entity


class CreateLinkTokenRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateLinkTokenRequest - a model defined in OpenAPI

        institution_id: The institution_id of this CreateLinkTokenRequest.
        entity: The entity of this CreateLinkTokenRequest.
        client_name: The client_name of this CreateLinkTokenRequest.
        session_client_secret: The session_client_secret of this CreateLinkTokenRequest.
        mx: The mx of this CreateLinkTokenRequest [Optional].
        plaid: The plaid of this CreateLinkTokenRequest [Optional].
    """

    institution_id: str = Field(alias="institution_id")
    entity: Entity = Field(alias="entity")
    client_name: str = Field(alias="client_name")
    session_client_secret: str = Field(alias="session_client_secret")
    mx: Optional[CreateLinkTokenRequestMx] = Field(alias="mx", default=None)
    plaid: Optional[CreateLinkTokenRequestPlaid] = Field(alias="plaid", default=None)

CreateLinkTokenRequest.update_forward_refs()
