# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class FinancialInstitutionLogo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    FinancialInstitutionLogo - a model defined in OpenAPI

        image: The image of this FinancialInstitutionLogo.
        type: The type of this FinancialInstitutionLogo.
        format: The format of this FinancialInstitutionLogo [Optional].
    """

    image: str = Field(alias="image")
    type: str = Field(alias="type")
    format: Optional[str] = Field(alias="format", default=None)

FinancialInstitutionLogo.update_forward_refs()
