# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from fuse_client.models.financial_connections_owner import FinancialConnectionsOwner


class GetFinancialConnectionsOwnersResponseAccountsInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetFinancialConnectionsOwnersResponseAccountsInner - a model defined in OpenAPI

        remote_account_id: The remote_account_id of this GetFinancialConnectionsOwnersResponseAccountsInner.
        owners: The owners of this GetFinancialConnectionsOwnersResponseAccountsInner.
        request_id: The request_id of this GetFinancialConnectionsOwnersResponseAccountsInner.
    """

    remote_account_id: str = Field(alias="remote_account_id")
    owners: List[FinancialConnectionsOwner] = Field(alias="owners")
    request_id: str = Field(alias="request_id")

GetFinancialConnectionsOwnersResponseAccountsInner.update_forward_refs()
