# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from fuse_client.models.migrate_financial_connections_aggregator_connection_data import MigrateFinancialConnectionsAggregatorConnectionData
from fuse_client.models.migrate_financial_connections_token_request_entity import MigrateFinancialConnectionsTokenRequestEntity
from fuse_client.models.product import Product


class MigrateFinancialConnectionsTokenRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MigrateFinancialConnectionsTokenRequest - a model defined in OpenAPI

        connection_data: The connection_data of this MigrateFinancialConnectionsTokenRequest.
        aggregator: The aggregator of this MigrateFinancialConnectionsTokenRequest.
        entity: The entity of this MigrateFinancialConnectionsTokenRequest.
        fuse_products: The fuse_products of this MigrateFinancialConnectionsTokenRequest.
    """

    connection_data: MigrateFinancialConnectionsAggregatorConnectionData = Field(alias="connection_data")
    aggregator: str = Field(alias="aggregator")
    entity: MigrateFinancialConnectionsTokenRequestEntity = Field(alias="entity")
    fuse_products: List[Product] = Field(alias="fuse_products")

MigrateFinancialConnectionsTokenRequest.update_forward_refs()
