# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SyncTransactionsResponseRemovedInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SyncTransactionsResponseRemovedInner - a model defined in OpenAPI

        transaction_id: The transaction_id of this SyncTransactionsResponseRemovedInner [Optional].
    """

    transaction_id: Optional[str] = Field(alias="transaction_id", default=None)

SyncTransactionsResponseRemovedInner.update_forward_refs()
