# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from fuse_client.models.aggregator import Aggregator


class UpdateEntityRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UpdateEntityRequest - a model defined in OpenAPI

        email: The email of this UpdateEntityRequest [Optional].
        aggregators: The aggregators of this UpdateEntityRequest [Optional].
        institution_ids: The institution_ids of this UpdateEntityRequest [Optional].
    """

    email: Optional[str] = Field(alias="email", default=None)
    aggregators: Optional[List[Aggregator]] = Field(alias="aggregators", default=None)
    institution_ids: Optional[List[str]] = Field(alias="institution_ids", default=None)

UpdateEntityRequest.update_forward_refs()
