# Generated by Django 3.2 on 2023-02-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perform', '0012_auto_20230218_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evalplanning',
            old_name='eval_date',
            new_name='eval_date_ind',
        ),
        migrations.AddField(
            model_name='evalplanning',
            name='eval_date_obj',
            field=models.DateField(blank=True, null=True),
        ),
    ]
