# Generated by Django 3.2.3 on 2023-03-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvadmin_third', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thirdusers',
            old_name='users',
            new_name='user',
        ),
    ]
