"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from fuse_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from fuse_client.exceptions import ApiAttributeError


def lazy_import():
    from fuse_client.model.transaction_merchant import TransactionMerchant
    globals()['TransactionMerchant'] = TransactionMerchant


class Transaction(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('category',): {
            'ACCESSORIES_STORE': "accessories_store",
            'ACCOUNTING_AND_BOOKKEEPING': "accounting_and_bookkeeping",
            'ACH': "ach",
            'ACORNS': "acorns",
            'ACUPUNCTURE': "acupuncture",
            'ADULT': "adult",
            'ADULT_EDUCATION': "adult_education",
            'ADULT_ENTERTAINMENT': "adult_entertainment",
            'ADVERTISING': "advertising",
            'ADVERTISING_AGENCIES_AND_MEDIA_BUYERS': "advertising_agencies_and_media_buyers",
            'ADVERTISING_AND_MARKETING': "advertising_and_marketing",
            'AFGHAN': "afghan",
            'AFRICAN': "african",
            'AGRICULTURE_AND_FORESTRY': "agriculture_and_forestry",
            'AIRLINES_AND_AVIATION_SERVICES': "airlines_and_aviation_services",
            'AIRPORTS': "airports",
            'ALCOHOL_AND_BARS': "alcohol_and_bars",
            'ALTERNATIVE_MEDICINE': "alternative_medicine",
            'AMERICAN': "american",
            'ANESTHESIOLOGISTS': "anesthesiologists",
            'ANIMAL_SHELTER': "animal_shelter",
            'ANTIQUES': "antiques",
            'APARTMENTS_CONDOS_AND_HOUSES': "apartments_condos_and_houses",
            'APPAREL_AND_FABRIC_PRODUCTS': "apparel_and_fabric_products",
            'AQUARIUM': "aquarium",
            'ARCADES_AND_AMUSEMENT_PARKS': "arcades_and_amusement_parks",
            'ARCHITECTS': "architects",
            'ART_AND_GRAPHIC_DESIGN': "art_and_graphic_design",
            'ART_DEALERS_AND_GALLERIES': "art_dealers_and_galleries",
            'ART_RESTORATION': "art_restoration",
            'ART_SCHOOL': "art_school",
            'ARTS_AND_CRAFTS': "arts_and_crafts",
            'ARTS_AND_ENTERTAINMENT': "arts_and_entertainment",
            'ASIAN': "asian",
            'ASSISTED_LIVING_SERVICES': "assisted_living_services",
            'ATHLETIC_FIELDS': "athletic_fields",
            'ATM': "atm",
            'ATMS': "atms",
            'AUCTIONS': "auctions",
            'AUDIOVISUAL': "audiovisual",
            'AUSTRALIAN': "australian",
            'AUTO_OIL_AND_LUBE': "auto_oil_and_lube",
            'AUTO_PAYMENT': "auto_payment",
            'AUTO_SMOG_CHECK': "auto_smog_check",
            'AUTO_TIRES': "auto_tires",
            'AUTO_TRANSMISSION': "auto_transmission",
            'AUTOMATION_AND_CONTROL_SYSTEMS': "automation_and_control_systems",
            'AUTOMOTIVE': "automotive",
            'BAGEL_SHOP': "bagel_shop",
            'BAKERY': "bakery",
            'BANK_FEES': "bank_fees",
            'BANKING_AND_FINANCE': "banking_and_finance",
            'BAR': "bar",
            'BARBECUE': "barbecue",
            'BASEBALL': "baseball",
            'BASKETBALL': "basketball",
            'BATTING_CAGES': "batting_cages",
            'BEACHES': "beaches",
            'BEAUTY_PRODUCTS': "beauty_products",
            'BED_AND_BREAKFASTS': "bed_and_breakfasts",
            'BEER_WINE_AND_SPIRITS': "beer_wine_and_spirits",
            'BENEFITS': "benefits",
            'BETTERMENT': "betterment",
            'BICYCLES': "bicycles",
            'BILL': "bill",
            'BILLIARDS_AND_POOL': "billiards_and_pool",
            'BILLPAY': "billpay",
            'BLOOD_BANKS_AND_CENTERS': "blood_banks_and_centers",
            'BOARDING_HOUSES': "boarding_houses",
            'BOAT': "boat",
            'BOAT_DEALERS': "boat_dealers",
            'BOATING': "boating",
            'BOOKSTORES': "bookstores",
            'BOUTIQUE': "boutique",
            'BOWLING': "bowling",
            'BRAZILIAN': "brazilian",
            'BREAKFAST_SPOT': "breakfast_spot",
            'BREWERIES': "breweries",
            'BUILDING_AND_LAND_SURVEYORS': "building_and_land_surveyors",
            'BUILDINGS_AND_STRUCTURES': "buildings_and_structures",
            'BURGERS': "burgers",
            'BURRITO': "burrito",
            'BUS_STATIONS': "bus_stations",
            'BUSINESS': "business",
            'BUSINESS_AND_STRATEGY_CONSULTING': "business_and_strategy_consulting",
            'BUSINESS_BROKERS_AND_FRANCHISES': "business_brokers_and_franchises",
            'BUSINESS_SERVICES': "business_services",
            'CABLE': "cable",
            'CAFE': "cafe",
            'CAJUN': "cajun",
            'CAMERAS': "cameras",
            'CAMPGROUNDS_AND_RV_PARKS': "campgrounds_and_rv_parks",
            'CANOES_AND_KAYAKS': "canoes_and_kayaks",
            'CAR_AND_TRUCK_RENTALS': "car_and_truck_rentals",
            'CAR_APPRAISERS': "car_appraisers",
            'CAR_DEALERS_AND_LEASING': "car_dealers_and_leasing",
            'CAR_PARTS_AND_ACCESSORIES': "car_parts_and_accessories",
            'CAR_SERVICE': "car_service",
            'CAR_WASH_AND_DETAIL': "car_wash_and_detail",
            'CARDIOLOGISTS': "cardiologists",
            'CARDS_AND_STATIONERY': "cards_and_stationery",
            'CARETAKERS': "caretakers",
            'CARIBBEAN': "caribbean",
            'CARPENTERS': "carpenters",
            'CARPET_AND_FLOORING': "carpet_and_flooring",
            'CASH_ADVANCE': "cash_advance",
            'CASINOS_AND_GAMING': "casinos_and_gaming",
            'CATERING': "catering",
            'CEMETERY': "cemetery",
            'CHARITIES_AND_NON-PROFITS': "charities_and_non-profits",
            'CHARITY': "charity",
            'CHARTER_BUSES': "charter_buses",
            'CHASE_QUICKPAY': "chase_quickpay",
            'CHECK': "check",
            'CHECK_CASHING': "check_cashing",
            'CHEMICALS_AND_GASSES': "chemicals_and_gasses",
            'CHILDCARE': "childcare",
            'CHILDREN': "children",
            'CHINESE': "chinese",
            'CHIROPRACTORS': "chiropractors",
            'CHURCHES': "churches",
            'CIRCUSES_AND_CARNIVALS': "circuses_and_carnivals",
            'CLASSIC_AND_ANTIQUE_CAR': "classic_and_antique_car",
            'CLEANING': "cleaning",
            'CLOTHING': "clothing",
            'CLOTHING_AND_ACCESSORIES': "clothing_and_accessories",
            'COAL': "coal",
            'COFFEE_SHOP': "coffee_shop",
            'COINBASE': "coinbase",
            'COLLECTIONS': "collections",
            'COLLEGES_AND_UNIVERSITIES': "colleges_and_universities",
            'COMBAT_SPORTS': "combat_sports",
            'COMMERCIAL_REAL_ESTATE': "commercial_real_estate",
            'COMMUNITY': "community",
            'COMPUTER_TRAINING': "computer_training",
            'COMPUTERS': "computers",
            'COMPUTERS_AND_ELECTRONICS': "computers_and_electronics",
            'COMPUTERS_AND_OFFICE_MACHINES': "computers_and_office_machines",
            'CONSTRUCTION': "construction",
            'CONSTRUCTION_SUPPLIES': "construction_supplies",
            'CONTRACTORS': "contractors",
            'CONVENIENCE_STORES': "convenience_stores",
            'CORPORATE_HOUSING': "corporate_housing",
            'CORRECTIONAL_INSTITUTIONS': "correctional_institutions",
            'COSTUMES': "costumes",
            'COTTAGES_AND_CABINS': "cottages_and_cabins",
            'COUNSELING_AND_THERAPY': "counseling_and_therapy",
            'COURTS': "courts",
            'CREATIVE_SERVICES': "creative_services",
            'CREDIT': "credit",
            'CREDIT_CARD': "credit_card",
            'CREDIT_COUNSELING_AND_BANKRUPTCY_SERVICES': "credit_counseling_and_bankruptcy_services",
            'CREDIT_REPORTING': "credit_reporting",
            'CROP_PRODUCTION': "crop_production",
            'CRUISES': "cruises",
            'CUBAN': "cuban",
            'CULINARY_LESSONS_AND_SCHOOLS': "culinary_lessons_and_schools",
            'CUPCAKE_SHOP': "cupcake_shop",
            'CYCLING': "cycling",
            'DANCE': "dance",
            'DANCE_AND_MUSIC': "dance_and_music",
            'DANCE_HALLS_AND_SALOONS': "dance_halls_and_saloons",
            'DANCE_SCHOOLS': "dance_schools",
            'DATING_AND_ESCORT': "dating_and_escort",
            'DAY_CARE_AND_PRESCHOOLS': "day_care_and_preschools",
            'DEBIT': "debit",
            'DELIS': "delis",
            'DENTISTS': "dentists",
            'DEPARTMENT_STORES': "department_stores",
            'DEPOSIT': "deposit",
            'DERMATOLOGISTS': "dermatologists",
            'DESSERT': "dessert",
            'DIGIT': "digit",
            'DIGITAL_PURCHASE': "digital_purchase",
            'DINERS': "diners",
            'DINING': "dining",
            'DIRECT_MAIL_AND_EMAIL_MARKETING_SERVICES': "direct_mail_and_email_marketing_services",
            'DISABLED_PERSONS_SERVICES': "disabled_persons_services",
            'DISCOUNT_STORES': "discount_stores",
            'DISTILLERY': "distillery",
            'DISTRIBUTION': "distribution",
            'DOCTORS_AND_DENTISTS': "doctors_and_dentists",
            'DONUTS': "donuts",
            'DOORS_AND_WINDOWS': "doors_and_windows",
            'DRIVING_SCHOOLS': "driving_schools",
            'DRUG_AND_ALCOHOL_SERVICES': "drug_and_alcohol_services",
            'DWOLLA': "dwolla",
            'EAR_NOSE_AND_THROAT': "ear_nose_and_throat",
            'EASTERN_EUROPEAN': "eastern_european",
            'EDUCATION': "education",
            'ELECTRIC': "electric",
            'ELECTRICAL_EQUIPMENT': "electrical_equipment",
            'ELECTRICAL_EQUIPMENT_AND_COMPONENTS': "electrical_equipment_and_components",
            'ELECTRICIANS': "electricians",
            'ELECTRONICS': "electronics",
            'EMERGENCY_SERVICES': "emergency_services",
            'EMPLOYMENT_AGENCIES': "employment_agencies",
            'ENGINEERING': "engineering",
            'ENTERTAINMENT': "entertainment",
            'ENVIRONMENTAL': "environmental",
            'EQUESTRIAN': "equestrian",
            'EQUIPMENT_RENTAL': "equipment_rental",
            'ETHIOPIAN': "ethiopian",
            'EVENTS_AND_EVENT_PLANNING': "events_and_event_planning",
            'EXCESS_ACTIVITY': "excess_activity",
            'FACILITIES_AND_NURSING_HOMES': "facilities_and_nursing_homes",
            'FAIRGROUNDS_AND_RODEOS': "fairgrounds_and_rodeos",
            'FALAFEL': "falafel",
            'FAMILY_MEDICINE': "family_medicine",
            'FARMERS_MARKETS': "farmers_markets",
            'FAST_FOOD': "fast_food",
            'FEE': "fee",
            'FENCES_FIREPLACES_AND_GARAGE_DOORS': "fences_fireplaces_and_garage_doors",
            'FILIPINO': "filipino",
            'FINANCIAL': "financial",
            'FINANCIAL_PLANNING_AND_INVESTMENTS': "financial_planning_and_investments",
            'FIRE_STATIONS': "fire_stations",
            'FISH_AND_CHIPS': "fish_and_chips",
            'FLEA_MARKETS': "flea_markets",
            'FLORISTS': "florists",
            'FOOD_AND_BEVERAGE': "food_and_beverage",
            'FOOD_AND_BEVERAGE_STORE': "food_and_beverage_store",
            'FOOD_AND_DRINK': "food_and_drink",
            'FOOD_TRUCK': "food_truck",
            'FOOTBALL': "football",
            'FOREIGN_TRANSACTION': "foreign_transaction",
            'FORESTRY': "forestry",
            'FORESTS': "forests",
            'FRATERNITIES_AND_SORORITIES': "fraternities_and_sororities",
            'FRAUD_DISPUTE': "fraud_dispute",
            'FRENCH': "french",
            'FUEL': "fuel",
            'FUEL_DEALER': "fuel_dealer",
            'FUND_RAISING': "fund_raising",
            'FUNERAL_SERVICES': "funeral_services",
            'FURNITURE_AND_FIXTURES': "furniture_and_fixtures",
            'FURNITURE_AND_HOME_DECOR': "furniture_and_home_decor",
            'GARDENS': "gardens",
            'GAS': "gas",
            'GAS_STATIONS': "gas_stations",
            'GASTROENTEROLOGISTS': "gastroenterologists",
            'GASTROPUB': "gastropub",
            'GENERAL': "general",
            'GENERAL_SURGERY': "general_surgery",
            'GEOLOGICAL': "geological",
            'GERMAN': "german",
            'GIFT_AND_NOVELTY': "gift_and_novelty",
            'GIFTS': "gifts",
            'GLASS_PRODUCTS': "glass_products",
            'GLASSES_AND_OPTOMETRIST': "glasses_and_optometrist",
            'GO_CARTS': "go_carts",
            'GOLF': "golf",
            'GOVERNMENT_DEPARTMENTS_AND_AGENCIES': "government_departments_and_agencies",
            'GOVERNMENT_LOBBYISTS': "government_lobbyists",
            'GREEK': "greek",
            'GUN_RANGES': "gun_ranges",
            'GYM': "gym",
            'GYMNASTICS': "gymnastics",
            'GYMS_AND_FITNESS_CENTERS': "gyms_and_fitness_centers",
            'HAIR_REMOVAL': "hair_removal",
            'HAIR_SALONS_AND_BARBERS': "hair_salons_and_barbers",
            'HARDWARE_AND_SERVICES': "hardware_and_services",
            'HARDWARE_STORE': "hardware_store",
            'HEALTH_FOOD': "health_food",
            'HEALTHCARE': "healthcare",
            'HEALTHCARE_SERVICES': "healthcare_services",
            'HEATING_VENTILATING_AND_AIR_CONDITIONING': "heating_ventilating_and_air_conditioning",
            'HELIPORTS': "heliports",
            'HIKING': "hiking",
            'HISTORIC_SITES': "historic_sites",
            'HOBBY_AND_COLLECTIBLES': "hobby_and_collectibles",
            'HOCKEY': "hockey",
            'HOLDING_AND_INVESTMENT_OFFICES': "holding_and_investment_offices",
            'HOME': "home",
            'HOME_APPLIANCES': "home_appliances",
            'HOME_IMPROVEMENT': "home_improvement",
            'HOME_INSPECTION_SERVICES': "home_inspection_services",
            'HOOKAH_LOUNGES': "hookah_lounges",
            'HOSPITALS_CLINICS_AND_MEDICAL_CENTERS': "hospitals_clinics_and_medical_centers",
            'HOSTELS': "hostels",
            'HOT_AIR_BALLOONS': "hot_air_balloons",
            'HOTEL_LOUNGE': "hotel_lounge",
            'HOTELS_AND_MOTELS': "hotels_and_motels",
            'HOUSEHOLD': "household",
            'HOUSEWARES': "housewares",
            'HOUSING_ASSISTANCE_AND_SHELTERS': "housing_assistance_and_shelters",
            'HUMAN_RESOURCES': "human_resources",
            'HUNTING_AND_FISHING': "hunting_and_fishing",
            'ICE_CREAM': "ice_cream",
            'IMMIGRATION': "immigration",
            'IMPORT_AND_EXPORT': "import_and_export",
            'INCOME': "income",
            'INDIAN': "indian",
            'INDONESIAN': "indonesian",
            'INDUSTRIAL_MACHINERY_AND_EQUIPMENT': "industrial_machinery_and_equipment",
            'INDUSTRIAL_MACHINERY_AND_VEHICLES': "industrial_machinery_and_vehicles",
            'INDUSTRIAL_SUPPLIES': "industrial_supplies",
            'INFRASTRUCTURE': "infrastructure",
            'INSUFFICIENT_FUNDS': "insufficient_funds",
            'INSURANCE': "insurance",
            'INTEREST': "interest",
            'INTEREST_CHARGED': "interest_charged",
            'INTEREST_EARNED': "interest_earned",
            'INTERIOR_DESIGN': "interior_design",
            'INTERNAL_ACCOUNT_TRANSFER': "internal_account_transfer",
            'INTERNAL_MEDICINE': "internal_medicine",
            'INTERNET': "internet",
            'INTERNET_CAFES': "internet_cafes",
            'INTERNET_SERVICES': "internet_services",
            'INVESTMENT': "investment",
            'ITALIAN': "italian",
            'JAPANESE': "japanese",
            'JAZZ_AND_BLUES_CAFE': "jazz_and_blues_cafe",
            'JEWELRY_AND_WATCHES': "jewelry_and_watches",
            'JUICE_BAR': "juice_bar",
            'KARAOKE': "karaoke",
            'KEEP_THE_CHANGE_SAVINGS_PROGRAM': "keep_the_change_savings_program",
            'KIDS': "kids",
            'KIDS&#39;_STORE': "kids'_store",
            'KITCHENS': "kitchens",
            'KOREAN': "korean",
            'LAKES': "lakes",
            'LANDMARKS': "landmarks",
            'LANDSCAPING_AND_GARDENERS': "landscaping_and_gardeners",
            'LATE_PAYMENT': "late_payment",
            'LATIN_AMERICAN': "latin_american",
            'LAUNDRY_AND_GARMENT_SERVICES': "laundry_and_garment_services",
            'LAW_ENFORCEMENT': "law_enforcement",
            'LAWN_AND_GARDEN': "lawn_and_garden",
            'LEATHER': "leather",
            'LEATHER_GOODS': "leather_goods",
            'LEGAL': "legal",
            'LIBRARIES': "libraries",
            'LIGHTING_FIXTURES': "lighting_fixtures",
            'LIMOS_AND_CHAUFFEURS': "limos_and_chauffeurs",
            'LINGERIE_STORE': "lingerie_store",
            'LIVESTOCK_AND_ANIMALS': "livestock_and_animals",
            'LOAN': "loan",
            'LOANS_AND_MORTGAGES': "loans_and_mortgages",
            'LODGES_AND_VACATION_RENTALS': "lodges_and_vacation_rentals",
            'LODGING': "lodging",
            'LOGGING_AND_SAWMILLS': "logging_and_sawmills",
            'LUGGAGE': "luggage",
            'MACHINE_SHOPS': "machine_shops",
            'MAINTENANCE_AND_REPAIR': "maintenance_and_repair",
            'MANAGEMENT': "management",
            'MANICURES_AND_PEDICURES': "manicures_and_pedicures",
            'MANUFACTURING': "manufacturing",
            'MARINE_SUPPLIES': "marine_supplies",
            'MARKET_RESEARCH_AND_CONSULTING': "market_research_and_consulting",
            'MASONRY': "masonry",
            'MASSAGE_CLINICS_AND_THERAPISTS': "massage_clinics_and_therapists",
            'MEDIA': "media",
            'MEDIA_PRODUCTION': "media_production",
            'MEDICAL_SUPPLIES_AND_LABS': "medical_supplies_and_labs",
            'MEDITERRANEAN': "mediterranean",
            'MEN&#39;S_STORE': "men's_store",
            'MENTAL_HEALTH': "mental_health",
            'METAL': "metal",
            'METAL_PRODUCTS': "metal_products",
            'METALS': "metals",
            'MEXICAN': "mexican",
            'MIDDLE_EASTERN': "middle_eastern",
            'MILITARY': "military",
            'MINIATURE_GOLF': "miniature_golf",
            'MINING': "mining",
            'MOBILE_HOMES': "mobile_homes",
            'MOBILE_PHONES': "mobile_phones",
            'MONUMENTS_AND_MEMORIALS': "monuments_and_memorials",
            'MOROCCAN': "moroccan",
            'MOSQUES': "mosques",
            'MOTORCYCLE_MOPED_AND_SCOOTER_REPAIR': "motorcycle_moped_and_scooter_repair",
            'MOTORCYCLES_MOPEDS_AND_SCOOTERS': "motorcycles_mopeds_and_scooters",
            'MOUNTAINS': "mountains",
            'MOVERS': "movers",
            'MOVIE_THEATRES': "movie_theatres",
            'MUSEUMS': "museums",
            'MUSIC_VIDEO_AND_DVD': "music_video_and_dvd",
            'MUSIC_AND_SHOW_VENUES': "music_and_show_venues",
            'MUSICAL_INSTRUMENTS': "musical_instruments",
            'NATURAL_PARKS': "natural_parks",
            'NEUROLOGISTS': "neurologists",
            'NEWS_REPORTING': "news_reporting",
            'NEWSSTANDS': "newsstands",
            'NIGHT_CLUBS': "night_clubs",
            'NIGHTLIFE': "nightlife",
            'NON-METALLIC_MINERALS': "non-metallic_minerals",
            'NONMETALLIC_MINERAL_PRODUCTS': "nonmetallic_mineral_products",
            'NURSES': "nurses",
            'NUTRITIONISTS': "nutritionists",
            'OBSTETRICIANS_AND_GYNECOLOGISTS': "obstetricians_and_gynecologists",
            'OFFICE': "office",
            'OFFICE_SUPPLIES': "office_supplies",
            'OIL_AND_GAS': "oil_and_gas",
            'ONCOLOGISTS': "oncologists",
            'ONLINE_ADVERTISING': "online_advertising",
            'ONLINE_SUBSCRIPTIONS': "online_subscriptions",
            'OPHTHALMOLOGISTS': "ophthalmologists",
            'OPTOMETRISTS': "optometrists",
            'ORGANIZATIONS_AND_ASSOCIATIONS': "organizations_and_associations",
            'ORTHOPEDIC_SURGEONS': "orthopedic_surgeons",
            'OTHER': "other",
            'OUTDOORS': "outdoors",
            'OUTLET': "outlet",
            'OVERDRAFT': "overdraft",
            'PACKAGING': "packaging",
            'PAINTBALL': "paintball",
            'PAINTING': "painting",
            'PAPER': "paper",
            'PAPER_PRODUCTS': "paper_products",
            'PARKING': "parking",
            'PARKS': "parks",
            'PARTY_CENTERS': "party_centers",
            'PATHOLOGISTS': "pathologists",
            'PAWN_SHOPS': "pawn_shops",
            'PAYMENT': "payment",
            'PAYPAL': "paypal",
            'PAYROLL': "payroll",
            'PEDIATRICIANS': "pediatricians",
            'PERSONAL_CARE': "personal_care",
            'PERSONAL_TRAINERS': "personal_trainers",
            'PEST_CONTROL': "pest_control",
            'PET': "pet",
            'PETROLEUM': "petroleum",
            'PETS': "pets",
            'PHARMACIES': "pharmacies",
            'PHONE': "phone",
            'PHOTOGRAPHY': "photography",
            'PHOTOS_AND_FRAMES': "photos_and_frames",
            'PHYSICAL_THERAPY': "physical_therapy",
            'PHYSICIANS': "physicians",
            'PICNIC_AREAS': "picnic_areas",
            'PIERCING': "piercing",
            'PIZZA': "pizza",
            'PLAID': "plaid",
            'PLASTIC_PRODUCTS': "plastic_products",
            'PLASTIC_SURGEONS': "plastic_surgeons",
            'PLASTICS': "plastics",
            'PLAYGROUNDS': "playgrounds",
            'PLUMBING': "plumbing",
            'PODIATRISTS': "podiatrists",
            'POLICE_STATIONS': "police_stations",
            'POOLS_AND_SPAS': "pools_and_spas",
            'PORTUGUESE': "portuguese",
            'POST_OFFICES': "post_offices",
            'PREGNANCY_AND_SEXUAL_HEALTH': "pregnancy_and_sexual_health",
            'PRIMARY_AND_SECONDARY_SCHOOLS': "primary_and_secondary_schools",
            'PRINT_TV_RADIO_AND_OUTDOOR_ADVERTISING': "print_tv_radio_and_outdoor_advertising",
            'PRINTING_AND_PUBLISHING': "printing_and_publishing",
            'PROMOTIONAL_ITEMS': "promotional_items",
            'PROPERTY_MANAGEMENT': "property_management",
            'PSYCHIATRISTS': "psychiatrists",
            'PSYCHICS_AND_ASTROLOGERS': "psychics_and_astrologers",
            'PSYCHOLOGISTS': "psychologists",
            'PUBLIC_AND_SOCIAL_SERVICES': "public_and_social_services",
            'PUBLIC_RELATIONS': "public_relations",
            'PUBLIC_TRANSPORTATION_SERVICES': "public_transportation_services",
            'RACE_TRACKS': "race_tracks",
            'RACQUET_SPORTS': "racquet_sports",
            'RACQUETBALL': "racquetball",
            'RADIOLOGISTS': "radiologists",
            'RAFTING': "rafting",
            'RAIL': "rail",
            'REAL_ESTATE': "real_estate",
            'REAL_ESTATE_AGENTS': "real_estate_agents",
            'REAL_ESTATE_APPRAISER': "real_estate_appraiser",
            'REAL_ESTATE_DEVELOPMENT_AND_TITLE_COMPANIES': "real_estate_development_and_title_companies",
            'RECREATION': "recreation",
            'RECREATION_CENTERS': "recreation_centers",
            'REFRIGERATION_AND_ICE': "refrigeration_and_ice",
            'REFUND': "refund",
            'RELIGIOUS': "religious",
            'RENEWABLE_ENERGY': "renewable_energy",
            'RENT': "rent",
            'REPAIR_SERVICES': "repair_services",
            'RESEARCH': "research",
            'RESORTS': "resorts",
            'RESPIRATORY': "respiratory",
            'RESTAURANTS': "restaurants",
            'RETIREMENT': "retirement",
            'RIDE_SHARE': "ride_share",
            'RIVERS': "rivers",
            'ROCK_CLIMBING': "rock_climbing",
            'ROOFERS': "roofers",
            'RUBBER': "rubber",
            'RUBBER_PRODUCTS': "rubber_products",
            'RUNNING': "running",
            'RVS_AND_MOTOR_HOMES': "rvs_and_motor_homes",
            'SALVAGE_YARDS': "salvage_yards",
            'SANITARY_AND_WASTE_MANAGEMENT': "sanitary_and_waste_management",
            'SAVE_AS_YOU_GO': "save_as_you_go",
            'SCANDINAVIAN': "scandinavian",
            'SCIENTIFIC': "scientific",
            'SCUBA_DIVING': "scuba_diving",
            'SEAFOOD': "seafood",
            'SEARCH_ENGINE_MARKETING_AND_OPTIMIZATION': "search_engine_marketing_and_optimization",
            'SECURITY_AND_SAFETY': "security_and_safety",
            'SENIOR_CITIZEN_SERVICES': "senior_citizen_services",
            'SERVICE': "service",
            'SERVICE_INSTRUMENTS': "service_instruments",
            'SERVICES': "services",
            'SHIPPING': "shipping",
            'SHIPPING_AND_FREIGHT': "shipping_and_freight",
            'SHOE_STORE': "shoe_store",
            'SHOPPING': "shopping",
            'SHOPPING_CENTERS_AND_MALLS': "shopping_centers_and_malls",
            'SHOPS': "shops",
            'SKATING': "skating",
            'SKIN_CARE': "skin_care",
            'SKYDIVING': "skydiving",
            'SNOW_SPORTS': "snow_sports",
            'SOCCER': "soccer",
            'SOCIAL_CLUBS': "social_clubs",
            'SOFTWARE': "software",
            'SOFTWARE_DEVELOPMENT': "software_development",
            'SPANISH': "spanish",
            'SPAS': "spas",
            'SPECIALTY': "specialty",
            'SPORT': "sport",
            'SPORTING_GOODS': "sporting_goods",
            'SPORTS_AND_RECREATION_CAMPS': "sports_and_recreation_camps",
            'SPORTS_BAR': "sports_bar",
            'SPORTS_CLUBS': "sports_clubs",
            'SPORTS_VENUES': "sports_venues",
            'SQUARE': "square",
            'SQUARE_CASH': "square_cash",
            'STADIUMS_AND_ARENAS': "stadiums_and_arenas",
            'STEAKHOUSES': "steakhouses",
            'STOCK_BROKERS': "stock_brokers",
            'STORAGE': "storage",
            'STRIP_CLUB': "strip_club",
            'STUDENT_AID_AND_GRANTS': "student_aid_and_grants",
            'SUBSCRIPTION': "subscription",
            'SUPERMARKETS_AND_GROCERIES': "supermarkets_and_groceries",
            'SUSHI': "sushi",
            'SWIMMING': "swimming",
            'SWIMMING_POOL_MAINTENANCE_AND_SERVICES': "swimming_pool_maintenance_and_services",
            'SWIMWEAR': "swimwear",
            'SWISS': "swiss",
            'SYMPHONY_AND_OPERA': "symphony_and_opera",
            'SYNAGOGUES': "synagogues",
            'TAILORS': "tailors",
            'TANNING_SALONS': "tanning_salons",
            'TATTOOING': "tattooing",
            'TAX': "tax",
            'TAXES': "taxes",
            'TAXI': "taxi",
            'TELECOMMUNICATION_SERVICES': "telecommunication_services",
            'TELEVISION': "television",
            'TEMPLE': "temple",
            'TENNIS': "tennis",
            'TEXTILES': "textiles",
            'THAI': "thai",
            'THEATRICAL_PRODUCTIONS': "theatrical_productions",
            'THIRD_PARTY': "third_party",
            'TOBACCO': "tobacco",
            'TOLLS_AND_FEES': "tolls_and_fees",
            'TOURIST_INFORMATION_AND_SERVICES': "tourist_information_and_services",
            'TOWING': "towing",
            'TOYS': "toys",
            'TRANSFER': "transfer",
            'TRANSPORT': "transport",
            'TRANSPORTATION': "transportation",
            'TRANSPORTATION_CENTERS': "transportation_centers",
            'TRANSPORTATION_EQUIPMENT': "transportation_equipment",
            'TRAVEL': "travel",
            'TRAVEL_AGENTS_AND_TOUR_OPERATORS': "travel_agents_and_tour_operators",
            'TREE_SERVICE': "tree_service",
            'TURKISH': "turkish",
            'TUTORING_AND_EDUCATIONAL_SERVICES': "tutoring_and_educational_services",
            'UPHOLSTERY': "upholstery",
            'UROLOGISTS': "urologists",
            'USED_CAR_DEALERS': "used_car_dealers",
            'UTILITIES': "utilities",
            'VEGAN_AND_VEGETARIAN': "vegan_and_vegetarian",
            'VENMO': "venmo",
            'VETERINARIANS': "veterinarians",
            'VIDEO_GAMES': "video_games",
            'VINTAGE_AND_THRIFT': "vintage_and_thrift",
            'VOCATIONAL_SCHOOLS': "vocational_schools",
            'WAREHOUSES_AND_WHOLESALE_STORES': "warehouses_and_wholesale_stores",
            'WATER': "water",
            'WATER_AND_WASTE_MANAGEMENT': "water_and_waste_management",
            'WATER_SPORTS': "water_sports",
            'WEB_DESIGN_AND_DEVELOPMENT': "web_design_and_development",
            'WEDDING_AND_BRIDAL': "wedding_and_bridal",
            'WELDING': "welding",
            'WHOLESALE': "wholesale",
            'WINE_BAR': "wine_bar",
            'WINERY': "winery",
            'WIRE': "wire",
            'WIRE_TRANSFER': "wire_transfer",
            'WITHDRAWAL': "withdrawal",
            'WOMEN&#39;S_STORE': "women's_store",
            'WOOD_PRODUCTS': "wood_products",
            'WRITING_COPYWRITING_AND_TECHNICAL_WRITING': "writing_copywriting_and_technical_writing",
            'YOGA_AND_PILATES': "yoga_and_pilates",
            'YOUTH_ORGANIZATIONS': "youth_organizations",
            'ZOO': "zoo",
        },
        ('status',): {
            'PENDING': "pending",
            'POSTED': "posted",
        },
        ('type',): {
            'ACH': "ach",
            'ADJUSTMENT': "adjustment",
            'ATM': "atm",
            'BANK_CHARGE': "bank_charge",
            'BILL_PAYMENT': "bill_payment",
            'CARD_PAYMENT': "card_payment",
            'CASH': "cash",
            'CASHBACK': "cashback",
            'CHARGE': "charge",
            'CHEQUE': "cheque",
            'CREDIT': "credit",
            'DEBIT': "debit",
            'DEPOSIT': "deposit",
            'DIGITAL_PAYMENT': "digital_payment",
            'DIRECT_DEBIT': "direct_debit",
            'FEE': "fee",
            'IN_STORE': "in_store",
            'INTEREST': "interest",
            'ONLINE': "online",
            'OTHER': "other",
            'PAYMENT': "payment",
            'PURCHASE': "purchase",
            'STANDING_ORDER': "standing_order",
            'TRANSACTION': "transaction",
            'TRANSFER': "transfer",
            'WIRE': "wire",
            'WITHDRAWAL': "withdrawal",
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'remote_id': (str,),  # noqa: E501
            'remote_account_id': (str,),  # noqa: E501
            'amount': (float,),  # noqa: E501
            'date': (str,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'category': ([str],),  # noqa: E501
            'merchant': (TransactionMerchant,),  # noqa: E501
            'status': (str,),  # noqa: E501
            'type': (str,),  # noqa: E501
            'remote_data': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
            'iso_currency_code': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'remote_id': 'remote_id',  # noqa: E501
        'remote_account_id': 'remote_account_id',  # noqa: E501
        'amount': 'amount',  # noqa: E501
        'date': 'date',  # noqa: E501
        'description': 'description',  # noqa: E501
        'category': 'category',  # noqa: E501
        'merchant': 'merchant',  # noqa: E501
        'status': 'status',  # noqa: E501
        'type': 'type',  # noqa: E501
        'remote_data': 'remote_data',  # noqa: E501
        'iso_currency_code': 'iso_currency_code',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, remote_id, remote_account_id, amount, date, description, category, merchant, status, type, remote_data, *args, **kwargs):  # noqa: E501
        """Transaction - a model defined in OpenAPI

        Args:
            remote_id (str): Remote Id of the transaction, ie Plaid or Teller Id
            remote_account_id (str): Remote Account Id of the transaction, ie Plaid Account Id
            amount (float): Amount in cents associated with the transaction. Positive values when money moves out of the account; negative values when money moves in. For example, debit card purchases are positive; credit card payments, direct deposits, and refunds are negative.
            date (str): Date of the transaction (YYYY-MM-DD)
            description (str): Description of the transaction
            category ([str]): Categories of the transaction, ie Computers and Electronics
            merchant (TransactionMerchant):
            status (str): The status of the transaction. This will be either posted or pending.
            type (str): Type of the transaction, ie adjustment
            remote_data (bool, date, datetime, dict, float, int, list, str, none_type):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            iso_currency_code (str): The ISO-4217 currency code of the transaction. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.remote_id = remote_id
        self.remote_account_id = remote_account_id
        self.amount = amount
        self.date = date
        self.description = description
        self.category = category
        self.merchant = merchant
        self.status = status
        self.type = type
        self.remote_data = remote_data
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, remote_id, remote_account_id, amount, date, description, category, merchant, status, type, remote_data, *args, **kwargs):  # noqa: E501
        """Transaction - a model defined in OpenAPI

        Args:
            remote_id (str): Remote Id of the transaction, ie Plaid or Teller Id
            remote_account_id (str): Remote Account Id of the transaction, ie Plaid Account Id
            amount (float): Amount in cents associated with the transaction. Positive values when money moves out of the account; negative values when money moves in. For example, debit card purchases are positive; credit card payments, direct deposits, and refunds are negative.
            date (str): Date of the transaction (YYYY-MM-DD)
            description (str): Description of the transaction
            category ([str]): Categories of the transaction, ie Computers and Electronics
            merchant (TransactionMerchant):
            status (str): The status of the transaction. This will be either posted or pending.
            type (str): Type of the transaction, ie adjustment
            remote_data (bool, date, datetime, dict, float, int, list, str, none_type):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            iso_currency_code (str): The ISO-4217 currency code of the transaction. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.remote_id = remote_id
        self.remote_account_id = remote_account_id
        self.amount = amount
        self.date = date
        self.description = description
        self.category = category
        self.merchant = merchant
        self.status = status
        self.type = type
        self.remote_data = remote_data
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
