
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-13T16:55:16-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "174ea982273b444d5063ebe94a2b5be002345a66",
 "version": "2.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
