from .base_declative_entity import Base
from sqlalchemy import Column, Integer, String, DateTime, Float


class Paciente(Base):
    __tablename__ = "TPACIENTE"

    id = Column(Integer, primary_key = True)
    nome = Column(String)
    datanascimento = Column("datanascimento", DateTime)
    rua = Column("rua", Integer)
    num = Column("num", String)
    telefone1 = Column("telefone1", String)
    telefone2 = Column("telefone2", String)
    email = Column("E-MAIL", String)
    naturalidade = Column("naturalidade", Float)
    nacionalidade = Column("nacionalidade", String)
    escolaridade = Column("escolaridade", Float)
    sexo = Column("sexo", String)
    cor = Column("cor", Float)
    estadocivil = Column("estadocivil", Float)
    identidade = Column("identidade", String)
    cpf = Column("cpf", String)
    datacadastro = Column("datacadastro", String)
    nomemae = Column("nomemae", String)
    nomepai = Column("nomepai", String)
    convenio = Column("convenio", Float)
    num_carteira_convenio = Column("num_carteira_convenio", String)
    num_cartao_sus = Column("num_cartao_sus", String)
    indicadopor = Column("indicadopor", String)
    cod_medico = Column("cod_medico", Float)
    observacoes = Column("observacoes", String)
    validade_carteira = Column("validade_carteira", DateTime)
    plano = Column("plano", String)
    complemento = Column("complemento", String)
    uf = Column("uf", String)
    inativo = Column("inativo", String)
    candidato_sus = Column("candidato_sus", String)
    autorizacao_sus = Column("autorizacao_sus", String)
    naturalidade2 = Column("naturalidade2", String)
    id_excluiu = Column("id_excluiu", Float)
    data_excluiu = Column("data_excluiu", DateTime)
    profissao = Column("profissao", String)
    conjuge = Column("conjuge", String)
    id_criou = Column("id_criou", Float)
    cep = Column("cep", String)
    dt_expedicao = Column("dt_expedicao", DateTime)
    motivo_excluir = Column("motivo_excluir", String)
    ultimo_cid = Column("ultimo_cid", String)
    ultimo_subcid = Column("ultimo_subcid", String)
    contato1 = Column("contato1", String)
    contato2 = Column("contato2", String)
    id_tipo = Column("id_tipo", Float)
    historia_clinica = Column("historia_clinica", String)
    dt_ultimaconsulta = Column("dt_ultimaconsulta", DateTime)
    foto = Column("foto", String)
    data_reserva = Column("data_reserva", DateTime)
    etnia = Column("etnia", String)
    cod_nacionalidade = Column("cod_nacionalidade", Float)
    motivo_pendencia = Column("motivo_pendencia", String)
    adm_verificar = Column("adm_verificar", String)
    var_com_titular = Column("var_com_titular", String)
    var_com_dependente = Column("var_com_dependente", String)
    celular = Column("celular", String)
    renda_familiar = Column("renda_familiar", String)
    pkidexterno = Column("pkidexterno", String)
    observacao_prontuario = Column("observacao_prontuario", String)
    emitiu_pasta = Column("emitiu_pasta", Integer)
    endereco = Column("endereco", String)
    codmunicipioibge = Column("codmunicipioibge", Integer)
    municipio = Column("municipio", String)
    bairro = Column("bairro", String)
