
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-09T17:43:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0316ab25c637a4a64f501505780623df0a1ac160",
 "version": "2.10.1b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
