# Generated by Django 3.2 on 2023-02-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perform', '0010_auto_20230217_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalplanning',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
