timezone_map = {
    'GMT': 'Greenwich Mean Time',
    'UTC': 'Universal Coordinated Time',
    'ECT': 'European Central Time',
    'EET': 'Eastern European Time',
    'ART': '(Arabic) Egypt Standard Time',
    'EAT': 'Eastern African Time',
    'MET': 'Middle East Time',
    'NET': 'Near East Time',
    'PLT': 'Pakistan Lahore Time',
    'IST': 'India Standard Time',
    'BST': 'Bangladesh Standard Time',
    'VST': 'Vietnam Standard Time',
    'CTT': 'China Taiwan Time',
    'JST': 'Japan Standard Time',
    'ACT': 'Australia Central Time',
    'AET': 'Australia Eastern Time',
    'SST': 'Solomon Standard Time',
    'NST': 'New Zealand Standard Time',
    'MIT': 'Midway Islands Time',
    'HDT': 'Hawaii Daylight Time',
    'HST': 'Hawaii Standard Time',
    'ADT': 'Alaska Daylight Time',
    'AST': 'Alaska Standard Time',
    'PDT': 'Pacific Daylight Time',
    'PST': 'Pacific Standard Time',
    'PNT': 'Phoenix Standard Time',
    'MDT': 'Mountain Daylight Time',
    'MST': 'Mountain Standard Time',
    'CDT': 'Central Daylight Time',
    'CST': 'Central Standard Time',
    'EDT': 'Eastern Daylight Time',
    'EST': 'Eastern Standard Time',
    'IET': 'Indiana Eastern Standard Time',
    'PRT': 'Puerto Rico and US Virgin Islands Time',
    'CNT': 'Canada Newfoundland Time',
    'AGT': 'Argentina Standard Time',
    'BET': 'Brazil Eastern Time',
    'CAT': 'Central African Time'
}

timezone_gmt_map = {
    'GMT': 'GMT',
    'UTC': 'GMT',
    'ECT': 'GMT+1:00',
    'EET': 'GMT+2:00',
    'ART': 'GMT+2:00',
    'EAT': 'GMT+3:00',
    'MET': 'GMT+3:30',
    'NET': 'GMT+4:00',
    'PLT': 'GMT+5:00',
    'IST': 'GMT+5:30',
    'BST': 'GMT+6:00',
    'VST': 'GMT+7:00',
    'CTT': 'GMT+8:00',
    'JST': 'GMT+9:00',
    'ACT': 'GMT+9:30',
    'AET': 'GMT+10:00',
    'SST': 'GMT+11:00',
    'NST': 'GMT+12:00',
    'MIT': 'GMT-11:00',
    'HDT': 'GMT-10:00',
    'HST': 'GMT-10:00',
    'ADT': 'GMT-9:00',
    'AST': 'GMT-9:00',
    'PDT': 'GMT-8:00',
    'PST': 'GMT-8:00',
    'PNT': 'GMT-7:00',
    'MDT': 'GMT-7:00',
    'MST': 'GMT-7:00',
    'CDT': 'GMT-6:00',
    'CST': 'GMT-6:00',
    'EDT': 'GMT-5:00',
    'EST': 'GMT-5:00',
    'IET': 'GMT-5:00',
    'PRT': 'GMT-4:00',
    'CNT': 'GMT-3:30',
    'AGT': 'GMT-3:00',
    'BET': 'GMT-3:00',
    'CAT': 'GMT-1:00'
}
