# Generated by Django 3.2.16 on 2023-03-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knightswhosayni', '0005_sale_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_email',
            field=models.CharField(default='test@localhost', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='contact_name',
            field=models.CharField(default='Tester', max_length=100),
            preserve_default=False,
        ),
    ]
