
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-13T17:04:58-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "88648f57ef714514b79cc1c82ef17b1ff33a8568",
 "version": "2.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
