"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse-client
from fuse-client.model.get_asset_report_request import GetAssetReportRequest


class TestGetAssetReportRequest(unittest.TestCase):
    """GetAssetReportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAssetReportRequest(self):
        """Test GetAssetReportRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAssetReportRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
