"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse-client
from fuse-client.model.financial_connections_investment_security_exchange import FinancialConnectionsInvestmentSecurityExchange


class TestFinancialConnectionsInvestmentSecurityExchange(unittest.TestCase):
    """FinancialConnectionsInvestmentSecurityExchange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFinancialConnectionsInvestmentSecurityExchange(self):
        """Test FinancialConnectionsInvestmentSecurityExchange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FinancialConnectionsInvestmentSecurityExchange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
