"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse-client
from fuse-client.model.refresh_asset_report_request import RefreshAssetReportRequest


class TestRefreshAssetReportRequest(unittest.TestCase):
    """RefreshAssetReportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRefreshAssetReportRequest(self):
        """Test RefreshAssetReportRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RefreshAssetReportRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
