"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse-client
from fuse-client.model.financial_connections_owner_addresses import FinancialConnectionsOwnerAddresses
from fuse-client.model.financial_connections_owner_emails import FinancialConnectionsOwnerEmails
from fuse-client.model.financial_connections_owner_names import FinancialConnectionsOwnerNames
from fuse-client.model.financial_connections_owner_phone_numbers import FinancialConnectionsOwnerPhoneNumbers
globals()['FinancialConnectionsOwnerAddresses'] = FinancialConnectionsOwnerAddresses
globals()['FinancialConnectionsOwnerEmails'] = FinancialConnectionsOwnerEmails
globals()['FinancialConnectionsOwnerNames'] = FinancialConnectionsOwnerNames
globals()['FinancialConnectionsOwnerPhoneNumbers'] = FinancialConnectionsOwnerPhoneNumbers
from fuse-client.model.financial_connections_owner import FinancialConnectionsOwner


class TestFinancialConnectionsOwner(unittest.TestCase):
    """FinancialConnectionsOwner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFinancialConnectionsOwner(self):
        """Test FinancialConnectionsOwner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FinancialConnectionsOwner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
