"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse-client
from fuse-client.model.sync_transactions_response_removed import SyncTransactionsResponseRemoved
from fuse-client.model.transaction import Transaction
globals()['SyncTransactionsResponseRemoved'] = SyncTransactionsResponseRemoved
globals()['Transaction'] = Transaction
from fuse-client.model.sync_transactions_response import SyncTransactionsResponse


class TestSyncTransactionsResponse(unittest.TestCase):
    """SyncTransactionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSyncTransactionsResponse(self):
        """Test SyncTransactionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SyncTransactionsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
