/* Generated by Cython 3.0.0a11 */

#ifndef __PYX_HAVE__inmoose__edgepy__edgepy_cpp
#define __PYX_HAVE__inmoose__edgepy__edgepy_cpp

#include "Python.h"

#ifndef __PYX_HAVE_API__inmoose__edgepy__edgepy_cpp

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyArrayObject *vector2ndarray(std::vector<double>  const &);
__PYX_EXTERN_C PyObject *make_levenberg_result(PyArrayObject *, PyArrayObject *, std::vector<double> , std::vector<long> , std::vector<char> );
__PYX_EXTERN_C void build_QRdecomposition(QRdecomposition *);
__PYX_EXTERN_C void decompose_QRdecomposition(QRdecomposition *);
__PYX_EXTERN_C void solve_QRdecomposition(QRdecomposition *);
__PYX_EXTERN_C void f77_dgemv(char const *, int const *, int const *, double const *, double const *, int const *, double const *, int const *, double const *, double *, int const *);
__PYX_EXTERN_C void f77_dpotrf(char const *, int const *, double *, int const *, int *);
__PYX_EXTERN_C void f77_dpotrs(char const *, int const *, int const *, double const *, int const *, double *, int const *, int *);
__PYX_EXTERN_C void f77_dsytrf(char const *, int const *, double *, int const *, int *, double *, int const *, int *);

#endif /* !__PYX_HAVE_API__inmoose__edgepy__edgepy_cpp */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initedgepy_cpp(void);
#else
/* WARNING: Use PyImport_AppendInittab("edgepy_cpp", PyInit_edgepy_cpp) instead of calling PyInit_edgepy_cpp directly from Python 3.5 */
PyMODINIT_FUNC PyInit_edgepy_cpp(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"edgepy_cpp\", PyInit_edgepy_cpp) instead of calling PyInit_edgepy_cpp directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"edgepy_cpp\", PyInit_edgepy_cpp) instead of calling PyInit_edgepy_cpp directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"edgepy_cpp\", PyInit_edgepy_cpp) instead of calling PyInit_edgepy_cpp directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_edgepy_cpp_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_edgepy_cpp() __PYX_WARN_IF_PyInit_edgepy_cpp_INIT_CALLED(PyInit_edgepy_cpp())
#endif
#endif

#endif /* !__PYX_HAVE__inmoose__edgepy__edgepy_cpp */
