class FixedVariables:
    def __init__() -> None: ...
    def insert(self, key: str | tuple[str, list[int]], value: float): ...
    def from_dict(dict) -> FixedVariables: ...
    def to_dict(self) -> dict: ...

class InstanceData:
    def __init__() -> None: ...
    def from_dict(dict) -> InstanceData: ...
    def insert(self, name: str, value): ...
    def to_dict(self) -> dict: ...
