
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-13T12:20:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f9b303c711a7df78b6d10f3d6f28b48d3d8e7ad",
 "version": "4.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
