# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.30.dev0+g9b64055.d20230412'
__version_tuple__ = version_tuple = (0, 0, 30, 'dev0', 'g9b64055.d20230412')
