# Generated by Django 3.2.16 on 2023-03-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knightswhosayni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='gumroad_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key',
            name='slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
