# Generated by Django 3.2.16 on 2023-03-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knightswhosayni', '0002_auto_20230307_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='module_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
