# Generated by Django 3.2.16 on 2023-03-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knightswhosayni', '0003_project_module_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(max_length=50)),
                ('sale_id', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
            ],
        ),
    ]
