# coding: utf-8

"""
    api-prediction

    API provides services for prediction module.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: developer@albertinvent.com
    Generated by: https://openapi-generator.tech
"""

from albert.api.paths.api_v3_productdesign_inventories_id.get import GetInventoriesBackUpdate
from albert.api.paths.api_v3_locations_async_id.get import GetLocBackUpdate
from albert.api.paths.api_v3_predictions_mergedac.post import ParentDacBulkUpdate
from albert.api.paths.api_v3_predictions_mergedat.post import ParentDatBulkUpdate
from albert.api.paths.api_v3_productdesign_mergeinventory.post import ParentInventoriesBulkUpdate
from albert.api.paths.api_v3_productdesign_inventories_id.put import PutInventoriesBackUpdate
from albert.api.paths.api_v3_locations_async_id.put import PutLocBackUpdate


class InternalApi(
    GetInventoriesBackUpdate,
    GetLocBackUpdate,
    ParentDacBulkUpdate,
    ParentDatBulkUpdate,
    ParentInventoriesBulkUpdate,
    PutInventoriesBackUpdate,
    PutLocBackUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
