
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-12T15:04:30-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "38ef30aaa4bf41197f0a946729e7c55e33119ae4",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
