
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-12T19:27:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a55ba5423d04d2ef7ac19356ccabc4c7906f577",
 "version": "1.2.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
