
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-12T10:13:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "66fc10cca770212c63a661c6a6c1a9bc9da12a35",
 "version": "v0.1.45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
