"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse_client
from fuse_client.model.aggregator import Aggregator
from fuse_client.model.fuse_api_error import FuseApiError
globals()['Aggregator'] = Aggregator
globals()['FuseApiError'] = FuseApiError
from fuse_client.model.fuse_api_error_data import FuseApiErrorData


class TestFuseApiErrorData(unittest.TestCase):
    """FuseApiErrorData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFuseApiErrorData(self):
        """Test FuseApiErrorData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FuseApiErrorData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
