"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse_client
from fuse_client.model.financial_connections_account_balance import FinancialConnectionsAccountBalance
globals()['FinancialConnectionsAccountBalance'] = FinancialConnectionsAccountBalance
from fuse_client.model.get_financial_connections_balance_response import GetFinancialConnectionsBalanceResponse


class TestGetFinancialConnectionsBalanceResponse(unittest.TestCase):
    """GetFinancialConnectionsBalanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetFinancialConnectionsBalanceResponse(self):
        """Test GetFinancialConnectionsBalanceResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetFinancialConnectionsBalanceResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
