"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse_client
from fuse_client.model.get_asset_report_response_report_historical_balances import GetAssetReportResponseReportHistoricalBalances


class TestGetAssetReportResponseReportHistoricalBalances(unittest.TestCase):
    """GetAssetReportResponseReportHistoricalBalances unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAssetReportResponseReportHistoricalBalances(self):
        """Test GetAssetReportResponseReportHistoricalBalances"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAssetReportResponseReportHistoricalBalances()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
