"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse_client
from fuse_client.model.migrate_financial_connections_token_request_entity import MigrateFinancialConnectionsTokenRequestEntity


class TestMigrateFinancialConnectionsTokenRequestEntity(unittest.TestCase):
    """MigrateFinancialConnectionsTokenRequestEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMigrateFinancialConnectionsTokenRequestEntity(self):
        """Test MigrateFinancialConnectionsTokenRequestEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MigrateFinancialConnectionsTokenRequestEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
