"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse_client
from fuse_client.model.migrate_financial_connections_aggregator_connection_data import MigrateFinancialConnectionsAggregatorConnectionData
from fuse_client.model.migrate_financial_connections_token_request_entity import MigrateFinancialConnectionsTokenRequestEntity
from fuse_client.model.product import Product
globals()['MigrateFinancialConnectionsAggregatorConnectionData'] = MigrateFinancialConnectionsAggregatorConnectionData
globals()['MigrateFinancialConnectionsTokenRequestEntity'] = MigrateFinancialConnectionsTokenRequestEntity
globals()['Product'] = Product
from fuse_client.model.migrate_financial_connections_token_request import MigrateFinancialConnectionsTokenRequest


class TestMigrateFinancialConnectionsTokenRequest(unittest.TestCase):
    """MigrateFinancialConnectionsTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMigrateFinancialConnectionsTokenRequest(self):
        """Test MigrateFinancialConnectionsTokenRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MigrateFinancialConnectionsTokenRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
