"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse_client
from fuse_client.model.financial_connections_account_institution import FinancialConnectionsAccountInstitution


class TestFinancialConnectionsAccountInstitution(unittest.TestCase):
    """FinancialConnectionsAccountInstitution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFinancialConnectionsAccountInstitution(self):
        """Test FinancialConnectionsAccountInstitution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FinancialConnectionsAccountInstitution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
