"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse_client
from fuse_client.model.financial_connections_owner import FinancialConnectionsOwner
from fuse_client.model.get_asset_report_response_report_balances import GetAssetReportResponseReportBalances
from fuse_client.model.get_asset_report_response_report_historical_balances import GetAssetReportResponseReportHistoricalBalances
globals()['FinancialConnectionsOwner'] = FinancialConnectionsOwner
globals()['GetAssetReportResponseReportBalances'] = GetAssetReportResponseReportBalances
globals()['GetAssetReportResponseReportHistoricalBalances'] = GetAssetReportResponseReportHistoricalBalances
from fuse_client.model.get_asset_report_response_report_accounts import GetAssetReportResponseReportAccounts


class TestGetAssetReportResponseReportAccounts(unittest.TestCase):
    """GetAssetReportResponseReportAccounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAssetReportResponseReportAccounts(self):
        """Test GetAssetReportResponseReportAccounts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAssetReportResponseReportAccounts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
