"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse_client
from fuse_client.model.get_investment_transactions_request_options import GetInvestmentTransactionsRequestOptions
globals()['GetInvestmentTransactionsRequestOptions'] = GetInvestmentTransactionsRequestOptions
from fuse_client.model.get_investment_transactions_request import GetInvestmentTransactionsRequest


class TestGetInvestmentTransactionsRequest(unittest.TestCase):
    """GetInvestmentTransactionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetInvestmentTransactionsRequest(self):
        """Test GetInvestmentTransactionsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetInvestmentTransactionsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
