# Generated by Django 4.1.5 on 2023-04-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formkit_ninja",
            "0007_alter_formcomponents_options_and_more_squashed_0028_formkitschemanode_additional_props_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="formkitschemanode",
            name="admin_key",
            field=models.CharField(help_text="Used as a human-readable label", max_length=1024, unique=True),
        ),
    ]
