# Generated by Django 4.1.5 on 2023-04-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_standardize_description_comments'),
        ('netbox_object_storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='s3cluster',
            name='contact',
        ),
        migrations.AddField(
            model_name='pool',
            name='contact',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s3pool_contact', to='tenancy.contact'),
        ),
        migrations.AddField(
            model_name='s3cluster',
            name='contact',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s3cluster_contact', to='tenancy.contact'),
        ),
    ]
