## településnevek iskolai feladatokhoz / Hungarian city names use: telepulesek list hu_city.telepulesek
telepulesek = [
    'Abony', 'Ajka', 'Albertirsa', 'Apagy', 'Aszód', 'Baja', 'Balassagyarmat', 'Balatonalmádi',
    'Balatonfüred', 'Balmazújváros', 'Barcs', 'Bátaszék', 'Békéscsaba', 'Bélapátfalva', 'Berettyóújfalu',
    'Biatorbágy', 'Bicske', 'Bóly', 'Budakeszi', 'Budaörs', 'Budapest', 'Cegléd', 'Celldömölk',
    'Cigánd', 'Csongrád', 'Csorna', 'Csurgó', 'Dabas', 'Debrecen', 'Dég', 'Dombóvár', 'Dunaharaszti',
    'Dunaújváros', 'Dunakeszi', 'Dunapataj', 'Dunaszentmiklós', 'Edelény', 'Eger', 'Encs', 'Érd',
    'Érpatak', 'Esztár', 'Fehérgyarmat', 'Fót', 'Gárdony', 'Göd', 'Gödöllő', 'Gyál', 'Gyomaendrőd',
    'Gyömrő', 'Gyöngyös', 'Gyula', 'Hajdúböszörmény', 'Hajdúhadház', 'Hajdúnánás', 'Halásztelek',
    'Harkány', 'Hatvan', 'Hévíz', 'Hódmezővásárhely', 'Ibrány', 'Isaszeg', 'Jánossomorja', 'Jászberény',
    'Kaba', 'Kalocsa', 'Kapuvár', 'Karcag', 'Kápolna', 'Kaposvár', 'Kapuvár', 'Karcag', 'Kazincbarcika',
    'Kecel', 'Kecskemét', 'Kemecse', 'Keszthely', 'Kisbér', 'Kiskőrös', 'Kiskunfélegyháza',
    'Kiskunhalas', 'Kiskunlacháza', 'Kisújszállás', 'Komárom', 'Komló', 'Környe', 'Kőszeg',
    'Kunhegyes', 'Lábatlan', 'Lajosmizse', 'Lenti', 'Létavértes', 'Levél', 'Maglód', 'Magyarbánhegyes',
    'Makó', 'Marcali', 'Martfű', 'Mátészalka', 'Mátraháza', 'Mátraverebély', 'Mátyásdomb',
    'Medgyesegyháza', 'Mezőberény', 'Mezőcsát', 'Mezőkövesd', 'Mezőtúr',
    'Miskolc', 'Mohács', 'Monor', 'Monorierdő', 'Mór', 'Mosonmagyaróvár', 'Múcsony', 'Munkács', 'Murfatlar',
    'Nagyatád', 'Nagybajom', 'Nagybátony', 'Nagyecsed', 'Nagyhalász', 'Nagykálló', 'Nagykáta', 'Nagykőrös',
    'Nagykovácsi', 'Nagymányok', 'Nagymaros', 'Nagymező', 'Nagyrábé', 'Nagytarcsa', 'Nemesgulács',
    'Nemesvámos', 'Nógrád', 'Nyírbátor', 'Nyíregyháza', 'Ócsa', 'Orosháza', 'Oroszlány', 'Oroszi',
    'Oszlár', 'Őrbottyán', 'Paks', 'Pálháza', 'Pápa', 'Pásztó', 'Pécs', 'Pécsvárad', 'Pellérd', 'Pétfürdő',
    'Pilis', 'Pilisvörösvár', 'Polgár', 'Pomáz', 'Püspökladány', 'Putnok', 'Ráckeve', 'Rákoscsaba', 'Rátka',
    'Recsk', 'Répcelak', 'Rétság', 'Rigács', 'Romhány', 'Rozsály', 'Ságvár', 'Sajószentpéter', 'Salgótarján',
    'Sárbogárd', 'Sáregres', 'Sárisáp', 'Sárospatak', 'Sárvár', 'Sásd', 'Sátoraljaújhely', 'Sellye',
    'Siófok', 'Solt', 'Somlóvásárhely', 'Sopron', 'Sümeg', 'Szabadbattyán', 'Szabadszállás', 'Szajol',
    'Szakoly', 'Szakonyfalu', 'Szarvas', 'Szatmárcseke', 'Szatymaz', 'Szebény', 'Szekszárd', 'Szentendre',
    'Szentgotthárd', 'Szentkirályszabadja', 'Szentlőrinckáta', 'Szentmártonkáta', 'Szenttamás', 'Szigetbecse',
    'Szigethalom', 'Szigetszentmárton', 'Szigetszentmiklós', 'Szigetvár', 'Szilvásvárad', 'Szirák', 'Szolnok',
    'Szombathely', 'Tab', 'Táborfalva', 'Tápiószecső', 'Tapolca', 'Tard', 'Tárnok']
