
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-12T23:18:51+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "77be3b3b946effe6430702911f81c4bc199f6e40",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
