# coding: utf-8

"""
    api-prediction

    API provides services for prediction module.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: developer@albertinvent.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from albert.api import schemas  # noqa: F401


class NewModelVersion(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "logTransform",
            "thresholds",
            "unitDictionary",
            "rootMeanSquare",
            "dataColumnId",
            "name",
            "albertId",
            "binlabels",
            "class",
            "version",
        }
        
        class properties:
            albertId = schemas.StrSchema
            name = schemas.StrSchema
            version = schemas.StrSchema
            
            
            class _class(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def GP(cls):
                    return cls("GP")
                
                @schemas.classproperty
                def LINEAR_REGRESSION(cls):
                    return cls("Linear Regression")
                
                @schemas.classproperty
                def RANDOM_FOREST(cls):
                    return cls("Random Forest")
                
                @schemas.classproperty
                def NEURAL_NETWORK(cls):
                    return cls("Neural Network")
                
                @schemas.classproperty
                def NN(cls):
                    return cls("NN")
            dataColumnId = schemas.StrSchema
            rootMeanSquare = schemas.IntSchema
            thresholds = schemas.StrSchema
            
            
            class binlabels(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'binlabels':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class unitDictionary(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'unitDictionary':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            logTransform = schemas.BoolSchema
            type = schemas.StrSchema
            dataColumnName = schemas.StrSchema
            
            
            class DataTemplates(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    
                    class items(
                        schemas.DictSchema
                    ):
                    
                    
                        class MetaOapg:
                            
                            class properties:
                                id = schemas.StrSchema
                                __annotations__ = {
                                    "id": id,
                                }
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
                        
                        @typing.overload
                        def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                        
                        def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", ], str]):
                            # dict_instance[name] accessor
                            return super().__getitem__(name)
                        
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                        
                        def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", ], str]):
                            return super().get_item_oapg(name)
                        
                    
                        def __new__(
                            cls,
                            *_args: typing.Union[dict, frozendict.frozendict, ],
                            id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
                            _configuration: typing.Optional[schemas.Configuration] = None,
                            **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                        ) -> 'items':
                            return super().__new__(
                                cls,
                                *_args,
                                id=id,
                                _configuration=_configuration,
                                **kwargs,
                            )
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, dict, frozendict.frozendict, ]], typing.List[typing.Union[MetaOapg.items, dict, frozendict.frozendict, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'DataTemplates':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            _45degree_angle_plot_train = schemas.StrSchema
            _45degree_angle_plot_test = schemas.StrSchema
            
            
            class totalEffectSensitivity(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'totalEffectSensitivity':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class mainEffectSensitivity(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'mainEffectSensitivity':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            trainedInputs = schemas.StrSchema
            
            
            class trainedInputsJSON(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'trainedInputsJSON':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            graduated = schemas.BoolSchema
            
            
            class hyperParameters(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'hyperParameters':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            totalDatapoints = schemas.IntSchema
            modelMetadata = schemas.StrSchema
            __annotations__ = {
                "albertId": albertId,
                "name": name,
                "version": version,
                "class": _class,
                "dataColumnId": dataColumnId,
                "rootMeanSquare": rootMeanSquare,
                "thresholds": thresholds,
                "binlabels": binlabels,
                "unitDictionary": unitDictionary,
                "logTransform": logTransform,
                "type": type,
                "dataColumnName": dataColumnName,
                "DataTemplates": DataTemplates,
                "45degreeAnglePlotTrain": _45degree_angle_plot_train,
                "45degreeAnglePlotTest": _45degree_angle_plot_test,
                "totalEffectSensitivity": totalEffectSensitivity,
                "mainEffectSensitivity": mainEffectSensitivity,
                "trainedInputs": trainedInputs,
                "trainedInputsJSON": trainedInputsJSON,
                "graduated": graduated,
                "hyperParameters": hyperParameters,
                "totalDatapoints": totalDatapoints,
                "modelMetadata": modelMetadata,
            }
    
    logTransform: MetaOapg.properties.logTransform
    thresholds: MetaOapg.properties.thresholds
    unitDictionary: MetaOapg.properties.unitDictionary
    rootMeanSquare: MetaOapg.properties.rootMeanSquare
    dataColumnId: MetaOapg.properties.dataColumnId
    name: MetaOapg.properties.name
    albertId: MetaOapg.properties.albertId
    binlabels: MetaOapg.properties.binlabels
    version: MetaOapg.properties.version
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["albertId"]) -> MetaOapg.properties.albertId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["version"]) -> MetaOapg.properties.version: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["class"]) -> MetaOapg.properties._class: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dataColumnId"]) -> MetaOapg.properties.dataColumnId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rootMeanSquare"]) -> MetaOapg.properties.rootMeanSquare: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["thresholds"]) -> MetaOapg.properties.thresholds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["binlabels"]) -> MetaOapg.properties.binlabels: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["unitDictionary"]) -> MetaOapg.properties.unitDictionary: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["logTransform"]) -> MetaOapg.properties.logTransform: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dataColumnName"]) -> MetaOapg.properties.dataColumnName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["DataTemplates"]) -> MetaOapg.properties.DataTemplates: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["45degreeAnglePlotTrain"]) -> MetaOapg.properties._45degree_angle_plot_train: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["45degreeAnglePlotTest"]) -> MetaOapg.properties._45degree_angle_plot_test: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["totalEffectSensitivity"]) -> MetaOapg.properties.totalEffectSensitivity: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mainEffectSensitivity"]) -> MetaOapg.properties.mainEffectSensitivity: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["trainedInputs"]) -> MetaOapg.properties.trainedInputs: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["trainedInputsJSON"]) -> MetaOapg.properties.trainedInputsJSON: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["graduated"]) -> MetaOapg.properties.graduated: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hyperParameters"]) -> MetaOapg.properties.hyperParameters: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["totalDatapoints"]) -> MetaOapg.properties.totalDatapoints: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["modelMetadata"]) -> MetaOapg.properties.modelMetadata: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["albertId", "name", "version", "class", "dataColumnId", "rootMeanSquare", "thresholds", "binlabels", "unitDictionary", "logTransform", "type", "dataColumnName", "DataTemplates", "45degreeAnglePlotTrain", "45degreeAnglePlotTest", "totalEffectSensitivity", "mainEffectSensitivity", "trainedInputs", "trainedInputsJSON", "graduated", "hyperParameters", "totalDatapoints", "modelMetadata", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["albertId"]) -> MetaOapg.properties.albertId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["version"]) -> MetaOapg.properties.version: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["class"]) -> MetaOapg.properties._class: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dataColumnId"]) -> MetaOapg.properties.dataColumnId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rootMeanSquare"]) -> MetaOapg.properties.rootMeanSquare: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["thresholds"]) -> MetaOapg.properties.thresholds: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["binlabels"]) -> MetaOapg.properties.binlabels: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["unitDictionary"]) -> MetaOapg.properties.unitDictionary: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["logTransform"]) -> MetaOapg.properties.logTransform: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dataColumnName"]) -> typing.Union[MetaOapg.properties.dataColumnName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["DataTemplates"]) -> typing.Union[MetaOapg.properties.DataTemplates, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["45degreeAnglePlotTrain"]) -> typing.Union[MetaOapg.properties._45degree_angle_plot_train, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["45degreeAnglePlotTest"]) -> typing.Union[MetaOapg.properties._45degree_angle_plot_test, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["totalEffectSensitivity"]) -> typing.Union[MetaOapg.properties.totalEffectSensitivity, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mainEffectSensitivity"]) -> typing.Union[MetaOapg.properties.mainEffectSensitivity, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["trainedInputs"]) -> typing.Union[MetaOapg.properties.trainedInputs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["trainedInputsJSON"]) -> typing.Union[MetaOapg.properties.trainedInputsJSON, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["graduated"]) -> typing.Union[MetaOapg.properties.graduated, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hyperParameters"]) -> typing.Union[MetaOapg.properties.hyperParameters, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["totalDatapoints"]) -> typing.Union[MetaOapg.properties.totalDatapoints, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["modelMetadata"]) -> typing.Union[MetaOapg.properties.modelMetadata, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["albertId", "name", "version", "class", "dataColumnId", "rootMeanSquare", "thresholds", "binlabels", "unitDictionary", "logTransform", "type", "dataColumnName", "DataTemplates", "45degreeAnglePlotTrain", "45degreeAnglePlotTest", "totalEffectSensitivity", "mainEffectSensitivity", "trainedInputs", "trainedInputsJSON", "graduated", "hyperParameters", "totalDatapoints", "modelMetadata", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        logTransform: typing.Union[MetaOapg.properties.logTransform, bool, ],
        thresholds: typing.Union[MetaOapg.properties.thresholds, str, ],
        unitDictionary: typing.Union[MetaOapg.properties.unitDictionary, dict, frozendict.frozendict, None, ],
        rootMeanSquare: typing.Union[MetaOapg.properties.rootMeanSquare, decimal.Decimal, int, ],
        dataColumnId: typing.Union[MetaOapg.properties.dataColumnId, str, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        albertId: typing.Union[MetaOapg.properties.albertId, str, ],
        binlabels: typing.Union[MetaOapg.properties.binlabels, dict, frozendict.frozendict, None, ],
        version: typing.Union[MetaOapg.properties.version, str, ],
        type: typing.Union[MetaOapg.properties.type, str, schemas.Unset] = schemas.unset,
        dataColumnName: typing.Union[MetaOapg.properties.dataColumnName, str, schemas.Unset] = schemas.unset,
        DataTemplates: typing.Union[MetaOapg.properties.DataTemplates, list, tuple, schemas.Unset] = schemas.unset,
        totalEffectSensitivity: typing.Union[MetaOapg.properties.totalEffectSensitivity, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        mainEffectSensitivity: typing.Union[MetaOapg.properties.mainEffectSensitivity, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        trainedInputs: typing.Union[MetaOapg.properties.trainedInputs, str, schemas.Unset] = schemas.unset,
        trainedInputsJSON: typing.Union[MetaOapg.properties.trainedInputsJSON, list, tuple, None, schemas.Unset] = schemas.unset,
        graduated: typing.Union[MetaOapg.properties.graduated, bool, schemas.Unset] = schemas.unset,
        hyperParameters: typing.Union[MetaOapg.properties.hyperParameters, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        totalDatapoints: typing.Union[MetaOapg.properties.totalDatapoints, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        modelMetadata: typing.Union[MetaOapg.properties.modelMetadata, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'NewModelVersion':
        return super().__new__(
            cls,
            *_args,
            logTransform=logTransform,
            thresholds=thresholds,
            unitDictionary=unitDictionary,
            rootMeanSquare=rootMeanSquare,
            dataColumnId=dataColumnId,
            name=name,
            albertId=albertId,
            binlabels=binlabels,
            version=version,
            type=type,
            dataColumnName=dataColumnName,
            DataTemplates=DataTemplates,
            totalEffectSensitivity=totalEffectSensitivity,
            mainEffectSensitivity=mainEffectSensitivity,
            trainedInputs=trainedInputs,
            trainedInputsJSON=trainedInputsJSON,
            graduated=graduated,
            hyperParameters=hyperParameters,
            totalDatapoints=totalDatapoints,
            modelMetadata=modelMetadata,
            _configuration=_configuration,
            **kwargs,
        )
