# Generated by Django 4.0.2 on 2023-04-10 03:14

import apps.moarc-framework.moarcframework.orm.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moarcframework', '0002_menu_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de creación')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('created_by', models.IntegerField(null=True, verbose_name='Creado por')),
                ('updated_by', models.IntegerField(null=True, verbose_name='Actualizado por')),
                ('name', apps.moarc-framework.moarcframework.orm.fields.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Nombre')),
                ('code', apps.moarc-framework.moarcframework.orm.fields.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Código')),
                ('prefix', apps.moarc-framework.moarcframework.orm.fields.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Prefijo')),
                ('suffix', apps.moarc-framework.moarcframework.orm.fields.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Sufijo')),
                ('current_number', apps.moarc-framework.moarcframework.orm.fields.IntegerField(default=1, verbose_name='Número actual')),
                ('start', apps.moarc-framework.moarcframework.orm.fields.IntegerField(default=1, verbose_name='Inicio')),
                ('padding', apps.moarc-framework.moarcframework.orm.fields.IntegerField(default=5, verbose_name='Fin')),
                ('increment', apps.moarc-framework.moarcframework.orm.fields.IntegerField(default=1, verbose_name='Paso')),
            ],
            options={
                'verbose_name': 'Secuencia',
                'verbose_name_plural': 'Secuencias',
                'db_table': 'base_sequence',
            },
        ),
    ]
