
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-09T14:02:21-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "39663a06fc9753d982b0f871a2304fb87f5f78fc",
 "version": "0.0.163"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
