
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-12T14:25:34-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "20559fdace20c8fb2a92cc572981a9155f06a71b",
 "version": "0.7.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
