# Generated by Django 3.2 on 2021-06-10 10:54

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcd_geo_db', '0005_rename_path_temp_division_path'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='division',
            index=django.contrib.postgres.indexes.GistIndex(fields=['path'], name='wcd_geo_db_division_path_index', opclasses=('gist_ltree_ops',)),
        ),
    ]
