# Generated by Django 3.2 on 2021-06-16 18:37

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wcd_geo_db', '0008_auto_20210615_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Code')),
                ('value', models.TextField(verbose_name='Value')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_set', to='wcd_geo_db.division', verbose_name='Code entity')),
            ],
            options={
                'verbose_name': 'Division code',
                'verbose_name_plural': 'Division codes',
            },
        ),
        migrations.AddIndex(
            model_name='divisioncode',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['code', 'value'], name='wcd_geo_db_divisioncode_cds_idx'),
        ),
    ]
