# Generated by Django 3.2.5 on 2021-08-03 08:32

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcd_geo_db', '0011_codes_to_array_merge'),
    ]

    operations = [
        TrigramExtension()
    ]
