# Generated by Django 3.2 on 2022-02-14 11:49

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcd_geo_db', '0013_auto_20210803_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='division',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='Polygon'),
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='place',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='Polygon'),
        ),
        migrations.AddField(
            model_name='route',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='route',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='Polygon'),
        ),
    ]
