# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: v23.3
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20069_capacity_trend_dates import InlineResponse20069CapacityTrendDates  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20069CapacityTrendDates(unittest.TestCase):
    """InlineResponse20069CapacityTrendDates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20069CapacityTrendDates(self):
        """Test InlineResponse20069CapacityTrendDates"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20069_capacity_trend_dates.InlineResponse20069CapacityTrendDates()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
