# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: v23.3
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20095_inventory_zone0_fd1_nvme3726_gb0_rpm import InlineResponse20095InventoryZone0FD1NVME3726GB0RPM  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20095InventoryZone0FD1NVME3726GB0RPM(unittest.TestCase):
    """InlineResponse20095InventoryZone0FD1NVME3726GB0RPM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20095InventoryZone0FD1NVME3726GB0RPM(self):
        """Test InlineResponse20095InventoryZone0FD1NVME3726GB0RPM"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20095_inventory_zone0_fd1_nvme3726_gb0_rpm.InlineResponse20095InventoryZone0FD1NVME3726GB0RPM()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
