# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: v23.3
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20095_inventory import InlineResponse20095Inventory  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20095Inventory(unittest.TestCase):
    """InlineResponse20095Inventory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20095Inventory(self):
        """Test InlineResponse20095Inventory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20095_inventory.InlineResponse20095Inventory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
