# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: v23.3
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20019_details import InlineResponse20019Details  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20019Details(unittest.TestCase):
    """InlineResponse20019Details unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20019Details(self):
        """Test InlineResponse20019Details"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20019_details.InlineResponse20019Details()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
